---
name: James A. Giles, MBChB (Hons) PhD
position: "Instructor, Vascular Neurology"
address: "Department of Neurology, Stroke Section\\tabularnewline Washington University School of Medicine\\tabularnewline Campus Box 8111, St. Louis, MO 63110, United States"
phone: +1 314 599 8624
email: "jamesagiles@gmail.com"
twitter: neurogiles
headcolor: 000088
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::hyndman
csl: vancouver-superscript-only-year.csl
---

\newcounter{bib}

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  cache = FALSE
)

library(tidyverse)
library(RefManageR)
library(vitae)

# Read any bib files
pubs <- bibliography_entries("Paperpile - Giles.bib")
#reports <- bibliography_entries("rjhreports.bib")
#packages <- bibliography_entries("Rpackages.bib")
```

# Some stuff about me

 * I poisoned myself doing research.
 * I was the first woman to win a Nobel prize
 * I was the first person and only woman to win a Nobel prize in two different sciences.

## Refereed research papers

```{r research-papers}

# Normal articles excluding editorials
pubs %>%
  filter(type == "article-journal")
```

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Informal studies", "1889-91", "Flying University", "Warsaw, Poland",
  "Master of Physics", "1893", "Sorbonne Université", "Paris, France",
  "Master of Mathematics", "1894", "Sorbonne Université", "Paris, France"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Nobel Prizes

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```


# Journal Publications


